<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | Token Expiration
    |--------------------------------------------------------------------------
    |
    | This value controls the number of days that API tokens are valid.
    | After this period, the token will expire and users will need to
    | re-authenticate. Default is 30 days.
    |
    */

    'token_expiration_days' => env('AUTH_TOKEN_EXPIRATION_DAYS', 30),

    /*
    |--------------------------------------------------------------------------
    | Token Prefix
    |--------------------------------------------------------------------------
    |
    | The prefix used when generating token names. This helps identify
    | tokens generated by this application.
    |
    */

    'token_prefix' => env('AUTH_TOKEN_PREFIX', 'erp'),

    /*
    |--------------------------------------------------------------------------
    | Cache TTL
    |--------------------------------------------------------------------------
    |
    | The time-to-live (in seconds) for cached authentication data.
    | This includes token validation results and permission checks.
    | Default is 1 hour (3600 seconds).
    |
    */

    'cache_ttl' => env('AUTH_CACHE_TTL', 3600),

    /*
    |--------------------------------------------------------------------------
    | Rate Limiting
    |--------------------------------------------------------------------------
    |
    | Configuration for authentication endpoint rate limiting.
    |
    */

    'rate_limit' => [
        'max_attempts' => env('AUTH_RATE_LIMIT_ATTEMPTS', 5),
        'decay_minutes' => env('AUTH_RATE_LIMIT_DECAY', 1),
    ],

    /*
    |--------------------------------------------------------------------------
    | Account Lockout
    |--------------------------------------------------------------------------
    |
    | Configuration for account lockout after failed login attempts.
    |
    */

    'lockout' => [
        'threshold' => env('AUTH_LOCKOUT_THRESHOLD', 5),
        'duration_minutes' => env('AUTH_LOCKOUT_DURATION', 30),
    ],

    /*
    |--------------------------------------------------------------------------
    | Password Reset
    |--------------------------------------------------------------------------
    |
    | Configuration for password reset functionality.
    |
    */

    'password_reset' => [
        'expiration_minutes' => env('AUTH_PASSWORD_RESET_EXPIRATION', 60),
        'token_length' => 64,
    ],

];
